In [6]:
from GridWorld_V1 import GridWorld_v1
import random
import numpy as np

In [ ]:
gamma = 0.9
theta = 0.001
rows = 5
columns = 5

fixed = [".....",".xx..","..x..",".x!x.",".x..."]
grid = GridWorld_v1(fixed=fixed)
grid.show_map()

np.set_printoptions(formatter={'float_kind': lambda x: f"{x:.1f}"})

value = np.zeros(rows*columns)
qtable = np.zeros((rows*columns,5))
policy = np.random.randint(0,5,size=(rows*columns))
grid.show_policy(policy)

[Grid World Map]
🟪🟪🟪🟪🟪
🟪❌❌🟪🟪
🟪🟪❌🟪🟪
🟪❌✅❌🟪
🟪❌🟪🟪🟪
[Policy Map]
🔄⬅️🔄🔄⬆️
⬇️⏬🔄➡️➡️
⬆️⬅️⏩️⬇️🔄
⬅️⏩️✅⏪🔄
⬆️⏪⬇️⬆️🔄


In [8]:
def policy_evaluation(grid, policy, value, gamma):
    #keeping integrity of function
    temp_value = value.copy()
    #evaluate each state
    for i in range(rows*columns):            
        #get the state value of the current state
        action = policy[i]
        score, nextState = grid.step(i, action)
        temp_value[i] = score + gamma* temp_value[nextState]        
    
    return temp_value

In [9]:
def policy_improvement(grid, value, gamma):
    
    for i in range(rows*columns):
        for j in range(5):
            score, nextState = grid.step(i,j)
            qtable[i][j] = score+gamma* value[nextState]
            
    new_policy = np.argmax(qtable,axis = 1)
    return new_policy

In [10]:
grid.show_map()
grid.show_policy
while True:
    old_policy = policy.copy()
    
    #policy evaluation
    while True:
        temp_value = policy_evaluation(grid, policy, value, gamma)
        delta = np.max(np.abs(temp_value - value))
        value = temp_value
        
        if delta < theta:
            break
    
    
    #policy improvement
    policy = policy_improvement(grid, value, gamma)
    
    grid.show_policy(policy)
    
    if np.array_equal(old_policy,policy):
        break
    
grid.print_value(value)
grid.show_policy(policy)

[Grid World Map]
🟪🟪🟪🟪🟪
🟪❌❌🟪🟪
🟪🟪❌🟪🟪
🟪❌✅❌🟪
🟪❌🟪🟪🟪
[Policy Map]
➡️➡️➡️⬅️⬅️
⬆️⏫️⏫️⬆️⬇️
⬆️⬅️⏪➡️⬇️
⬆️⏫️✅⏩️⬆️
🔄⏫️⬆️➡️⬆️
[Policy Map]
➡️➡️➡️➡️⬇️
⬆️⏫️⏫️⬆️⬆️
⬆️⬅️⏬⬆️⬆️
⬆️⏩️✅⏪⬆️
⬆️⏩️⬆️⬅️⬆️
[Policy Map]
➡️➡️➡️➡️⬇️
⬆️⏫️⏬⬆️⬆️
⬆️➡️⏬⬇️⬆️
➡️⏩️✅⏪⬅️
➡️⏩️⬆️⬅️⬅️
[Policy Map]
➡️➡️⬇️➡️⬇️
⬆️⏬⏬⬇️⬆️
➡️➡️⏬⬇️⬇️
➡️⏩️✅⏪⬅️
⬆️⏩️⬆️⬅️⬅️
[Policy Map]
➡️➡️⬇️⬇️⬇️
⬇️⏬⏬⬇️⬇️
➡️➡️⏬⬇️⬇️
➡️⏩️✅⏪⬅️
⬆️⏩️⬆️⬅️⬅️
[Policy Map]
⬇️➡️⬇️⬇️⬇️
⬇️⏬⏬⬇️⬇️
➡️➡️⏬⬇️⬇️
➡️⏩️✅⏪⬅️
⬆️⏩️⬆️⬅️⬅️
[Policy Map]
⬇️➡️⬇️⬇️⬇️
⬇️⏬⏬⬇️⬇️
➡️➡️⏬⬇️⬇️
➡️⏩️✅⏪⬅️
⬆️⏩️⬆️⬅️⬅️
[value]
[[ 5.8  5.6  6.2  6.5  5.8]
 [ 6.5  7.2  8.   7.2  6.5]
 [ 7.2  8.  10.   8.   7.2]
 [ 8.  10.  10.  10.   8. ]
 [ 7.2  9.  10.   9.   8.1]]
[Policy Map]
⬇️➡️⬇️⬇️⬇️
⬇️⏬⏬⬇️⬇️
➡️➡️⏬⬇️⬇️
➡️⏩️✅⏪⬅️
⬆️⏩️⬆️⬅️⬅️
